#if defined(UART_API_HAVE_9383C_CAMERA) && defined(RR_DRV_SW_CAMERA_LASERCAM)

#define MAX_DATA_SIZE   (1 << 10)
#define CAMERA_EEPROM_SLIGHT_FILESIZE         0x54    //10*8+4=84
#define CAMERA_EEPROM_SLIGHT_FILE_NAME  "/mnt/reserve/camera_slight.bin"

typedef struct {
    float plane[4];
    float translation[3];
    float quaternion[4];
    float reserved[10];
} camera_extrinsics_t;

extern int rca_camera_read_slight_data(camera_extrinsics_t
        *camera_slight_parap);
extern int rca_camera_write_slight_data(unsigned char *data);

#define CAMERA_EEPROM_MAX_REG_SIZE          0x2000
#define CAMERA_EEPROM_READ_RETRY_TIMES      3
#define CAMERA_EEPROM_RR_MAIN_VERSION       1
#define CAMERA_EEPROM_RR_SUB_VERSION        0

#define CAMERA_EEPROM_BLOCK0_REG_ADDR       0x0000
#define CAMERA_EEPROM_BLOCK0_DATASIZE       0xA0

#define CAMERA_EEPROM_BLOCK1_REG_ADDR       0x0EA3
#define CAMERA_IDS0_EEPROM_BLOCK1_DATASIZE       0x154
#define CAMERA_IDS1_EEPROM_BLOCK1_DATASIZE       0xc4

#define CAMERA_EEPROM_VERSION_REG_ADDR      0x0000
#define CAMERA_EEPROM_VERSION_OFFSET        (CAMERA_EEPROM_VERSION_REG_ADDR - CAMERA_EEPROM_BLOCK0_REG_ADDR)
#define CAMERA_EEPROM_VERSION_DATASIZE      (0x10)

#define CAMERA_EEPROM_RESERVE_REG_ADDR      0x0010
#define CAMERA_EEPROM_RESERVE_OFFSET        (CAMERA_EEPROM_RESERVE_REG_ADDR - CAMERA_EEPROM_BLOCK0_REG_ADDR)
#define CAMERA_EEPROM_RESERVE_DATASIZE      (0x88 + 0x08)    //10*8+4 + sizeof(rrCameraHeadInfoSt)

#define CAMERA_EEPROM_PARA_REG_ADDR         0x0EA3
#define CAMERA_EEPROM_PARA_OFFSET           (CAMERA_EEPROM_PARA_REG_ADDR - CAMERA_EEPROM_BLOCK1_REG_ADDR)
#define CAMERA_EEPROM_PARA_DATASIZE         (0x54 + 0x08)    //10*8+4 + sizeof(rrCameraHeadInfoSt)

#define CAMERA_EEPROM_SLIGHT_REG_ADDR       0x0EFF
#define CAMERA_EEPROM_SLIGHT_OFFSET         (CAMERA_EEPROM_SLIGHT_REG_ADDR - CAMERA_EEPROM_BLOCK1_REG_ADDR)
#define CAMERA_EEPROM_SLIGHT_DATASIZE       (0xF0 + 0x08)    //60*4 + sizeof(rrCameraHeadInfoSt)

#define CAMERA_EEPROM_DEPTH_REG_ADDR        0x0EFF
#define CAMERA_EEPROM_DEPTH_OFFSET         (CAMERA_EEPROM_DEPTH_REG_ADDR - CAMERA_EEPROM_BLOCK1_REG_ADDR)
#define CAMERA_EEPROM_DEPTH_DATASIZE       (0x60 + 0x08)    //24*4 + sizeof(rrCameraHeadInfoSt)

#define CAMERA_EEPROM_RESERVE_VER           0x01
#define CAMERA_EEPROM_RESERVE_ID            0x01
#define CAMERA_EEPROM_RESERVE_FILESIZE      0x88   //8+32*4

#define CAMERA_EEPROM_SLIGHT_VER            0x01
#define CAMERA_EEPROM_SLIGHT_ID             0x02
// #define CAMERA_EEPROM_SLIGHT_FILESIZE       0xF0    //60*4=240

#define CAMERA_EEPROM_PARA_VER              0x01
#define CAMERA_EEPROM_PARA_ID               0x03
#define CAMERA_EEPROM_PARA_FILESIZE         0x54    //10*8+4=84

#define CAMERA_EEPROM_DEPTH_VER             0x01
#define CAMERA_EEPROM_DEPTH_ID              0x04
#define CAMERA_EEPROM_DEPTH_FILESIZE        0x60    //10*8+4=84
//OTP
#define CAMERA_EEPROM_OTP_REG_ADDR          0x1000
#define CAMERA_EEPROM_FUSE_REG_ADDR         0x1004
#define CAMERA_EEPROM_SUPPLIER_REG_ADDR     0x1014
#define CAMERA_EEPROM_OC_REG_ADDR           0x1015
#define CAMERA_EEPROM_MSC_REG_ADDR          0x101B
#define CAMERA_EEPROM_FILTER_REG_ADDR       0x161D
#define CAMERA_EEPROM_BAND_REG_ADDR         0x161E
#define CAMERA_EEPROM_BLEMISH_REG_ADDR      0x1621
#define CAMERA_EEPROM_AWB_REG_ADDR          0x1639


#define CAMERA_EEPROM_FUSE_OFFSET           (CAMERA_EEPROM_FUSE_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_SUPPLIER_OFFSET       (CAMERA_EEPROM_SUPPLIER_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_OC_OFFSET             (CAMERA_EEPROM_OC_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_MSC_OFFSET            (CAMERA_EEPROM_MSC_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_FILTER_OFFSET         (CAMERA_EEPROM_FILTER_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_BAND_OFFSET         (CAMERA_EEPROM_BAND_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_BLEMISH_OFFSET        (CAMERA_EEPROM_BLEMISH_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)
#define CAMERA_EEPROM_AWB_OFFSET            (CAMERA_EEPROM_AWB_REG_ADDR - CAMERA_EEPROM_OTP_REG_ADDR)

#define CAMERA_EEPROM_OTP_DATASIZE          (0x620 + 1) //include check sum,except blemish&awb
#define CAMERA_EEPROM_OTP_ALL_DATASIZE      (0x646 + 1) //include check sum
#define CAMERA_EEPROM_FUSE_DATASIZE         (0x10)
#define CAMERA_EEPROM_MODULE_DATASIZE       (0x19 + 1)  //ID&OC include check sum
#define CAMERA_EEPROM_MSC_DATASIZE          (0x600 + 1) //include check sum
#define CAMERA_EEPROM_LASER_DATASIZE        (0x2 + 1) //include check sum
#define CAMERA_EEPROM_BLEMISH_DATASIZE      (0x17 + 1) //include check sum
#define CAMERA_EEPROM_AWB_DATASIZE          (0xC + 1) //include check sum
#endif